/**
 * Comprehensive course data with 30+ courses across IT and Non-IT categories
 */

// Helper function to convert weeks to days
const weeksToDays = (weeks) => weeks * 7

export const generateComprehensiveCourses = () => {
  const courses = [
    // ===== FRONTEND DEVELOPMENT =====
    {
      id: 'course-1',
      title: 'React for Beginners',
      description: 'Learn React from scratch with practical examples and projects',
      category: 'Frontend Development',
      price: 499,
      thumbnail: 'https://images.unsplash.com/photo-1633356122544-f134324ef6db?w=500&h=300&fit=crop',
      instructorName: 'React Master',
      studentCount: 245,
      duration: '4 weeks',
      durationDays: weeksToDays(4),
      rating: 4.8,
    },
    {
      id: 'course-2',
      title: 'JavaScript Fundamentals',
      description: 'Master JavaScript basics and advanced concepts',
      category: 'Frontend Development',
      price: 399,
      thumbnail: 'https://images.unsplash.com/photo-1579468118864-1b9ea3c0db3a?w=500&h=300&fit=crop',
      instructorName: 'JS Expert',
      studentCount: 512,
      duration: '3 weeks',
      durationDays: weeksToDays(3),
      rating: 4.9,
    },
    {
      id: 'course-3',
      title: 'Vue.js Complete Guide',
      description: 'Build modern web applications with Vue.js',
      category: 'Frontend Development',
      price: 549,
      thumbnail: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=500&h=300&fit=crop',
      instructorName: 'Vue Master',
      studentCount: 189,
      duration: '5 weeks',
      durationDays: weeksToDays(5),
      rating: 4.7,
    },
    {
      id: 'course-4',
      title: 'Advanced React Patterns',
      description: 'Master advanced React patterns and best practices',
      category: 'Frontend Development',
      price: 699,
      thumbnail: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=500&h=300&fit=crop',
      instructorName: 'React Expert',
      studentCount: 156,
      duration: '6 weeks',
      durationDays: weeksToDays(6),
      rating: 4.8,
    },
    {
      id: 'course-5',
      title: 'CSS & Responsive Design',
      description: 'Master CSS3 and create responsive web designs',
      category: 'Frontend Development',
      price: 349,
      thumbnail: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=500&h=300&fit=crop',
      instructorName: 'Design Expert',
      studentCount: 423,
      duration: '3 weeks',
      durationDays: weeksToDays(3),
      rating: 4.6,
    },

    // ===== BACKEND DEVELOPMENT =====
    {
      id: 'course-6',
      title: 'Node.js Backend Development',
      description: 'Build scalable backend applications with Node.js and Express',
      category: 'Backend Development',
      price: 599,
      thumbnail: 'https://images.unsplash.com/photo-1627873649417-af36141a4016?w=500&h=300&fit=crop',
      instructorName: 'Backend Expert',
      studentCount: 334,
      duration: '6 weeks',
      durationDays: weeksToDays(6),
      rating: 4.8,
    },
    {
      id: 'course-7',
      title: 'Python Backend Development',
      description: 'Build web applications with Python and Django',
      category: 'Backend Development',
      price: 649,
      thumbnail: 'https://images.unsplash.com/photo-1526374965328-7f5ae4e8b08f?w=500&h=300&fit=crop',
      instructorName: 'Python Expert',
      studentCount: 267,
      duration: '7 weeks',
      durationDays: weeksToDays(7),
      rating: 4.7,
    },
    {
      id: 'course-8',
      title: 'REST API Design & Development',
      description: 'Design and build robust REST APIs',
      category: 'Backend Development',
      price: 549,
      thumbnail: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=500&h=300&fit=crop',
      instructorName: 'API Expert',
      studentCount: 198,
      duration: '4 weeks',
      durationDays: weeksToDays(4),
      rating: 4.9,
    },

    // ===== FULL STACK DEVELOPMENT =====
    {
      id: 'course-9',
      title: 'MERN Stack Complete Bootcamp',
      description: 'Build full-stack applications with MongoDB, Express, React, Node.js',
      category: 'Full Stack Development',
      price: 899,
      thumbnail: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=500&h=300&fit=crop',
      instructorName: 'Full Stack Master',
      studentCount: 456,
      duration: '12 weeks',
      durationDays: weeksToDays(12),
      rating: 4.9,
    },
    {
      id: 'course-10',
      title: 'LAMP Stack Development',
      description: 'Build web applications with Linux, Apache, MySQL, PHP',
      category: 'Full Stack Development',
      price: 499,
      thumbnail: 'https://images.unsplash.com/photo-1627873649417-af36141a4016?w=500&h=300&fit=crop',
      instructorName: 'PHP Expert',
      studentCount: 234,
      duration: '8 weeks',
      durationDays: weeksToDays(8),
      rating: 4.5,
    },

    // ===== DATA SCIENCE & AI =====
    {
      id: 'course-11',
      title: 'Python for Data Science',
      description: 'Learn Python programming for data analysis and machine learning',
      category: 'Data Science',
      price: 699,
      thumbnail: 'https://images.unsplash.com/photo-1526374965328-7f5ae4e8b08f?w=500&h=300&fit=crop',
      instructorName: 'Data Scientist',
      studentCount: 389,
      duration: '8 weeks',
      durationDays: weeksToDays(8),
      rating: 4.8,
    },
    {
      id: 'course-12',
      title: 'Machine Learning Fundamentals',
      description: 'Introduction to machine learning algorithms and applications',
      category: 'Machine Learning',
      price: 749,
      thumbnail: 'https://images.unsplash.com/photo-1526374965328-7f5ae4e8b08f?w=500&h=300&fit=crop',
      instructorName: 'ML Expert',
      studentCount: 312,
      duration: '6 weeks',
      durationDays: weeksToDays(6),
      rating: 4.7,
    },
    {
      id: 'course-13',
      title: 'Deep Learning with TensorFlow',
      description: 'Master deep learning and neural networks',
      category: 'Artificial Intelligence',
      price: 899,
      thumbnail: 'https://images.unsplash.com/photo-1526374965328-7f5ae4e8b08f?w=500&h=300&fit=crop',
      instructorName: 'AI Expert',
      studentCount: 267,
      duration: '8 weeks',
      durationDays: weeksToDays(8),
      rating: 4.8,
    },
    {
      id: 'course-14',
      title: 'Natural Language Processing',
      description: 'Learn NLP techniques and applications',
      category: 'Artificial Intelligence',
      price: 799,
      thumbnail: 'https://images.unsplash.com/photo-1526374965328-7f5ae4e8b08f?w=500&h=300&fit=crop',
      instructorName: 'NLP Specialist',
      studentCount: 145,
      duration: '6 weeks',
      durationDays: weeksToDays(6),
      rating: 4.6,
    },

    // ===== CYBERSECURITY =====
    {
      id: 'course-15',
      title: 'Cybersecurity Fundamentals',
      description: 'Learn cybersecurity principles and practices',
      category: 'Cybersecurity',
      price: 699,
      thumbnail: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=500&h=300&fit=crop',
      instructorName: 'Security Expert',
      studentCount: 234,
      duration: '5 weeks',
      durationDays: weeksToDays(5),
      rating: 4.7,
    },
    {
      id: 'course-16',
      title: 'Ethical Hacking & Penetration Testing',
      description: 'Master ethical hacking and security testing',
      category: 'Cybersecurity',
      price: 899,
      thumbnail: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=500&h=300&fit=crop',
      instructorName: 'Hacking Expert',
      studentCount: 178,
      duration: '8 weeks',
      durationDays: weeksToDays(8),
      rating: 4.8,
    },

    // ===== CLOUD & DEVOPS =====
    {
      id: 'course-17',
      title: 'AWS Cloud Fundamentals',
      description: 'Learn Amazon Web Services cloud computing',
      category: 'Cloud Computing',
      price: 799,
      thumbnail: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=500&h=300&fit=crop',
      instructorName: 'Cloud Expert',
      studentCount: 456,
      duration: '5 weeks',
      durationDays: weeksToDays(5),
      rating: 4.8,
    },
    {
      id: 'course-18',
      title: 'Docker & Kubernetes',
      description: 'Master containerization and orchestration',
      category: 'DevOps',
      price: 749,
      thumbnail: 'https://images.unsplash.com/photo-1627873649417-af36141a4016?w=500&h=300&fit=crop',
      instructorName: 'DevOps Expert',
      studentCount: 289,
      duration: '6 weeks',
      durationDays: weeksToDays(6),
      rating: 4.7,
    },
    {
      id: 'course-19',
      title: 'CI/CD Pipeline Development',
      description: 'Build continuous integration and deployment pipelines',
      category: 'DevOps',
      price: 699,
      thumbnail: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=500&h=300&fit=crop',
      instructorName: 'Pipeline Expert',
      studentCount: 156,
      duration: '4 weeks',
      durationDays: weeksToDays(4),
      rating: 4.6,
    },

    // ===== MOBILE DEVELOPMENT =====
    {
      id: 'course-20',
      title: 'React Native Mobile Development',
      description: 'Build cross-platform mobile apps with React Native',
      category: 'Mobile App Development',
      price: 699,
      thumbnail: 'https://images.unsplash.com/photo-1512941691920-25bda36dc643?w=500&h=300&fit=crop',
      instructorName: 'Mobile Expert',
      studentCount: 345,
      duration: '7 weeks',
      durationDays: weeksToDays(7),
      rating: 4.7,
    },
    {
      id: 'course-21',
      title: 'Flutter App Development',
      description: 'Create beautiful mobile apps with Flutter',
      category: 'Mobile App Development',
      price: 649,
      thumbnail: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=500&h=300&fit=crop',
      instructorName: 'Flutter Expert',
      studentCount: 267,
      duration: '6 weeks',
      durationDays: weeksToDays(6),
      rating: 4.8,
    },

    // ===== DESIGN =====
    {
      id: 'course-22',
      title: 'UI/UX Design Masterclass',
      description: 'Master user interface and user experience design',
      category: 'UI/UX Design',
      price: 549,
      thumbnail: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=500&h=300&fit=crop',
      instructorName: 'Design Master',
      studentCount: 423,
      duration: '6 weeks',
      durationDays: weeksToDays(6),
      rating: 4.8,
    },
    {
      id: 'course-23',
      title: 'Graphic Design Essentials',
      description: 'Learn graphic design principles and tools',
      category: 'Graphic Design',
      price: 449,
      thumbnail: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=500&h=300&fit=crop',
      instructorName: 'Graphics Expert',
      studentCount: 312,
      duration: '5 weeks',
      durationDays: weeksToDays(5),
      rating: 4.7,
    },
    {
      id: 'course-24',
      title: 'Photography Masterclass',
      description: 'Learn professional photography techniques',
      category: 'Photography',
      price: 399,
      thumbnail: 'https://images.unsplash.com/photo-1606986628025-35d57e735ae0?w=500&h=300&fit=crop',
      instructorName: 'Photography Pro',
      studentCount: 234,
      duration: '4 weeks',
      durationDays: weeksToDays(4),
      rating: 4.6,
    },
    {
      id: 'course-25',
      title: 'Video Editing & Production',
      description: 'Master video editing and production techniques',
      category: 'Video Editing',
      price: 499,
      thumbnail: 'https://images.unsplash.com/photo-1598899134739-24c46f58b8c0?w=500&h=300&fit=crop',
      instructorName: 'Video Expert',
      studentCount: 189,
      duration: '5 weeks',
      durationDays: weeksToDays(5),
      rating: 4.7,
    },

    // ===== BUSINESS & ENTREPRENEURSHIP =====
    {
      id: 'course-26',
      title: 'Digital Marketing Essentials',
      description: 'Learn digital marketing strategies and tools',
      category: 'Digital Marketing',
      price: 349,
      thumbnail: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=500&h=300&fit=crop',
      instructorName: 'Marketing Expert',
      studentCount: 567,
      duration: '4 weeks',
      durationDays: weeksToDays(4),
      rating: 4.8,
    },
    {
      id: 'course-27',
      title: 'Business Fundamentals',
      description: 'Learn core business concepts and entrepreneurship',
      category: 'Business & Entrepreneurship',
      price: 399,
      thumbnail: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=500&h=300&fit=crop',
      instructorName: 'Business Coach',
      studentCount: 445,
      duration: '6 weeks',
      durationDays: weeksToDays(6),
      rating: 4.7,
    },
    {
      id: 'course-28',
      title: 'Finance & Accounting Basics',
      description: 'Master financial management and accounting principles',
      category: 'Finance & Accounting',
      price: 449,
      thumbnail: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=500&h=300&fit=crop',
      instructorName: 'Finance Expert',
      studentCount: 334,
      duration: '5 weeks',
      durationDays: weeksToDays(5),
      rating: 4.6,
    },
    {
      id: 'course-29',
      title: 'Project Management Essentials',
      description: 'Learn project management methodologies and tools',
      category: 'Project Management',
      price: 399,
      thumbnail: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=500&h=300&fit=crop',
      instructorName: 'PM Expert',
      studentCount: 289,
      duration: '4 weeks',
      durationDays: weeksToDays(4),
      rating: 4.7,
    },

    // ===== SOFT SKILLS =====
    {
      id: 'course-30',
      title: 'Public Speaking for Beginners',
      description: 'Master the art of public speaking and presentation',
      category: 'Public Speaking',
      price: 299,
      thumbnail: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=500&h=300&fit=crop',
      instructorName: 'Speaking Coach',
      studentCount: 612,
      duration: '3 weeks',
      durationDays: weeksToDays(3),
      rating: 4.8,
    },
    {
      id: 'course-31',
      title: 'Communication Skills Mastery',
      description: 'Improve your communication and interpersonal skills',
      category: 'Communication Skills',
      price: 349,
      thumbnail: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=500&h=300&fit=crop',
      instructorName: 'Communication Expert',
      studentCount: 523,
      duration: '4 weeks',
      durationDays: weeksToDays(4),
      rating: 4.7,
    },
    {
      id: 'course-32',
      title: 'Personal Development & Growth',
      description: 'Unlock your potential and achieve personal growth',
      category: 'Personal Development',
      price: 299,
      thumbnail: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=500&h=300&fit=crop',
      instructorName: 'Life Coach',
      studentCount: 678,
      duration: '6 weeks',
      durationDays: weeksToDays(6),
      rating: 4.8,
    },
    {
      id: 'course-33',
      title: 'Language Learning: English',
      description: 'Master English language skills',
      category: 'Language Learning',
      price: 399,
      thumbnail: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=500&h=300&fit=crop',
      instructorName: 'Language Expert',
      studentCount: 445,
      duration: '8 weeks',
      durationDays: weeksToDays(8),
      rating: 4.6,
    },

    // ===== SPECIALIZED TECH =====
    {
      id: 'course-34',
      title: 'Blockchain Development',
      description: 'Learn blockchain technology and smart contracts',
      category: 'Blockchain Development',
      price: 899,
      thumbnail: 'https://images.unsplash.com/photo-1639762681033-6461efb0efa8?w=500&h=300&fit=crop',
      instructorName: 'Blockchain Expert',
      studentCount: 156,
      duration: '8 weeks',
      durationDays: weeksToDays(8),
      rating: 4.7,
    },
    {
      id: 'course-35',
      title: 'Game Development with Unity',
      description: 'Create games with Unity game engine',
      category: 'Game Development',
      price: 749,
      thumbnail: 'https://images.unsplash.com/photo-1538481143235-5d630a5bba20?w=500&h=300&fit=crop',
      instructorName: 'Game Dev Expert',
      studentCount: 234,
      duration: '10 weeks',
      durationDays: weeksToDays(10),
      rating: 4.8,
    },
  ]

  return courses.map((course) => ({
    ...course,
    content: `Complete guide to ${course.title}`,
    instructorId: 'demo-instructor',
    createdAt: new Date(),
    updatedAt: new Date(),
  }))
}

export default { generateComprehensiveCourses }
